# Site settings
title: Oltre Nuove Frontiere
email: author@oltrenuovefrontiere.it
description: Blog Personale per condividere le esperienze sulla Nuova Evangelizzazione.
baseurl: "" 
url: "http://www.oltrenuovefrontiere.it”
twitter_username: lucachristille
github_username:  lucachristille

timezone: Europe/Rome

# Build settings
markdown: kramdown
