title:            Site Title
description:      Describe your website here.
disqus_shortname: shortname
# Your site's domain goes here. When working locally use localhost server leave blank
# PS. If you set this wrong stylesheets and scripts won't load and most links will break.
# PPS. If you leave it blank for local testing home links won't work, they'll be fine for live domains though.
url:              http://lucachristille.github.io/oltre-nuove-frontiere/

# Owner/author information
owner:
  name:           Luca Christille
  avatar:         avatar.jpg
  bio:            "Cristiano aderente a @rnsitalia, sposo di Elisa, équipe AEGiovani per Piemonte/VdA, Pastorale di Servizio di un gruppo RnS, studio Psicologia"
  email:          author@oltrenuovefrontiere.it
  # Social networking links used in footer. Update and remove as you like.
  twitter: lucachristille       
  facebook: lucachristille      

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
  - title: Theme Setup
    url: /theme-setup
  - title: External Link
    url: http://mademistakes.com
    external: false

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Rome
future:      true
markdown:    kramdown

# Amount of posts to show on home page
paginate: 5